# Generated by Django 5.1.6 on 2025-03-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={},
        ),
        migrations.AlterModelManagers(
            name="users",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="users",
            name="Email",
        ),
        migrations.RemoveField(
            model_name="users",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="users",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="users",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="users",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="users",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="users",
            name="password",
        ),
        migrations.RemoveField(
            model_name="users",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="users",
            name="username",
        ),
        migrations.AlterField(
            model_name="event",
            name="EventID",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="eventID"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="RegistrationID",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="registrationID"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="UserID",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="userID"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.CharField(max_length=50, verbose_name="email"),
        ),
    ]
